kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb
  labels:
    app.kubernetes.io/name: influxdb
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"
